### ISSUE TITLE
CUDA out of memory. Tried to allocate 78.00 MiB

### ISSUE THREAD

**Issue by calltovijay** [googlecolab/colabtools#1761]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Getting the runtime error while training the model using PyTorch framework with GPU option for the past 24 hrs. RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 15.90 GiB total capacity; 14.84 GiB already allocated; 65.88 MiB free; 15.02 GiB reserved in total by PyTorch)
- Describe the expected behavior:
I was able to run this model until last week without any runtime error.  I have my project deadline by 10th Dec 2020. Please fix it asap.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
  Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
 
![image](https://user-images.githubusercontent.com/6165644/101358445-796af280-3860-11eb-934b-adb70e3e8c01.png)

**Comment by calltovijay** [comment]
Tried restarting the sessions and runtimes many times. No luck. Please fix it asap or let me know if there is a work around.
Thanks in advance.

**Comment by RIT20** [comment]
CUDA out of memory. Tried to allocate 626.00 MiB (GPU 0; 7.43 GiB total capacity; 6.43 GiB already allocated; 66.94 MiB free; 6.73 GiB reserved in total by PyTorch)
showing this  in my notebook , the  same notebook is working till day before yesterday.., tried resetting runtime, restarting it.., the same error has shown. please solve this...

**Comment by CodyBurker** [comment]
I ran into this too. Decreasing batch size worked for me.
