### ISSUE TITLE
The GPU runtime I was assigned with card "A100-SXM4-40GB" can't be used with pytorch

### ISSUE THREAD

**Issue by usergenic** [googlecolab/colabtools#2287]
**Describe the current behavior**
I'm paying for Google Colab Pro+ and the GPU runtime I'm on can't run CUDA.  According to nvidia-smi:
```
# nvidia-smi
Sun Sep 26 04:12:30 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    49W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

When I try to use pytorch/CUDA I get this error message:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Describe the expected behavior**
Normally I get some kind of Tesla GPU and everything is fine.  I guess this machine is misconfigured or shouldn't be considered a GPU runtime based on current library requirements.  Sucks, because I can't do ANYTHING about it except disconnect and hope to get a different one in several hours or whenever the colab system decides to reassign me one.

**What web browser you are using**
Chrome.  Expect browser is irrelevant here.

**Comment by usergenic** [comment]
Looks like the error may be a pytorch version incompatibility with the card and upgrading https://github.com/pytorch/pytorch/issues/49161 has solved these kinds of problems before.  I can't get it to work even with an explicit upgrade attempt.  Looks like the machine comes with 1.9.0 anyways.  Don't know what to do.

**Comment by usergenic** [comment]
Aha.  This fixed my problem:

```
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by colaboratory-team** [comment]
@usergenic thanks for reporting and for offering a workaround for users who run into this.
Internally tracked as b/201220232.

**Comment by therealjustlike** [comment]
> Aha. This fixed my problem:
> 
> ```
> pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
> ```

Hi usergenic, I've made a new cell and when I run this line you shared I get this error:

  File "<ipython-input-6-eb52a58b3f43>", line 1
    pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
               ^
SyntaxError: invalid syntax

**Comment by ArthurConmy** [comment]
> > Aha. This fixed my problem:
> > ```
> > pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
> > ```
> 
> Hi usergenic, I've made a new cell and when I run this line you shared I get this error:
> 
> File "", line 1 pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html ^ SyntaxError: invalid syntax

Use `!pip3` not `pip3`

**Comment by DocSuzie** [comment]
Same problem... Do I need to run this command every time I connect? It fixed my first session, but now I just started a new session and the same problem.

**Comment by colaboratory-team** [comment]
This should be resolved in today's release (where the cu111 wheels are preinstalled instead of the cu102 wheels).
If you're still seeing issues later today, "Factory reset runtime" in the Runtime menu or the command palette should get you an updated VM.

**Comment by robinsloan** [comment]
Hi @colaboratory-team, question for you: this update caused one of my notebooks to break, and it took a while to track down the root cause / find this comment in this issue. Is there a Colab changelog published anywhere? I looked, but couldn't find one. It would be a great addition!

**Comment by robinsloan** [comment]
Ah, fabulous! Just a thought… I was surprised to discover there is (apparently?) no Colab blog; I think there ought to be! Both to provide an obvious/"discoverable" platform for technical announcements like this, AND for the broader opportunity to talk about your work, the stuff the Colab team is excited about, and even highlight interesting uses, interesting notebooks…!

(I have often said that I think Colab is the most legitimately futuristic thing going, so obviously I think this should be a whole wonderful magazine-like website, not just a blog... but I would settle for a blog... 😝)

**Comment by x4nth055** [comment]
> Aha. This fixed my problem:
> 
> ```
> pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
> ```

As of yesterday, the error is raised again when using A100-SXM4-40GB, when I restart the VM and get V100, it works normally. The above workaround doesn't work either. Any help?

**Comment by codestamp** [comment]
I am also getting a similar type of error while running a simple Vector addition program on Colab. "Error: no kernel image is available for execution on the device"

I think it has to do something with CUDA compiler.
