### ISSUE TITLE
System Crash when Creating Keras Model

### ISSUE THREAD

**Issue by gtonychuo** [googlecolab/colabtools#2486]
**Describe the current behavior**
When creating new model with keras_model_sequential(), the [Colab R Kernel](https://colab.to/r) crashes
with the error message "Your session crashed. Automatically restarting" and the error log entries ...
2021-12-07 13:58:02.898480: W tensorflow/stream_executor/cuda/cuda_driver.cc:374] A non-primary context 0x5629d02fb000 for device 0 exists before initializing the StreamExecutor. The primary context is now 0x5629cf2748a0. We haven't verified StreamExecutor works with that.
2021-12-07 13:58:02.904893: F tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error INTERNAL: failed initializing StreamExecutor for CUDA device ordinal 0: INTERNAL: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN: unknown error

**Describe the expected behavior**
The code used to work well in both CPU and GPU.  However, it only work with CPU now. The system always crash when we choose to use the GPU accelerator.

**What web browser you are using**
Chrome

**Additional context**
[a minimal notebook that demo the bug](https://colab.research.google.com/drive/1vhNrXOMbDEgUjjtx4aqlzHMNIg_u5B1X?usp=sharing)  This code used to work well in both CPU and GPU.  However, it only work with CPU now. The system always crash when we choose to use the GPU accelerator.

**Comment by craigcitro** [comment]
OK, I have a better idea what's going on here: R is tweaking `LD_LIBRARY_PATH` on startup, and accidentally loading the *wrong* copy of libcuda, leading to a failure to initialize the GPU.

Here's a *terrible* workaround/hack until we get this fixed: https://colab.research.google.com/gist/craigcitro/50a1cc16af93bd35fdc1fcd7ee6de5e1/system-crash-when-creating-keras-model-r.ipynb

Note that there are two steps: (1) tweak a file on disk, and then (2) restart the kernel. Note that (2) must happen *before* installing packages.

**Comment by gtonychuo** [comment]
@craigcitro The "work around"  works for me.  Thank you very much!  Hope we will have a fix soon.

**Comment by gtonychuo** [comment]
Dear @craigcitro ,  Do you know why we need to install the `keras`  package every time when we start a R-Kernel?  I meant, what prevent us from preinstalling `keras` in the R environment like we did for the rest of the R packages?
