### ISSUE TITLE
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by Salman-F** [googlecolab/colabtools#2578]
I can't execute my notebook because of cuDNN. My Program stop right when the first epoch starts.

I expected that my augmentation funciton ends and the the models starts the epoch.
I alos tried the solution of another issue. I tried to restart all runtimes but that didnt work.

i am using chrome.

I am very new to machine learning and it could be a problem in the code. but i cant identify the problem with that error message.

Notebook: https://gist.github.com/Salman-F/d74c46895a61e220f28852d2915d212d#file-training-ipynb

**Comment by craigcitro** [comment]
I suspect your problem is that you're running `!pip install tensorflow-gpu` and picking up a version that's incompatible with the libraries/hardware available on Colab runtimes.

TF is always preinstalled and set up to work with the existing GPU; no install should be necessary.

**Comment by Salman-F** [comment]
Thank you, that helped me. I get the same TF Version 2.7.0 but the error doesn't appear anymore :)
