### ISSUE TITLE
CUDA cuInit: Unknown CUDA error value?

### ISSUE THREAD

**Issue by jangyeunyoon** [googlecolab/colabtools#2827]
I using colab on blender rendering GPU

suddenly it appear warning

how i fix it out?

CUDA cuInit: Unknown CUDA error value
F0523 17:11:21.172250   499 device.cpp:402] Device does not support queues.
*** Check failure stack trace: ***
    @          0x2b6cefd  (unknown)
    @          0x2b6ee03  (unknown)
    @          0x2b6ca8d  (unknown)
    @          0x2b6f6d9  (unknown)
    @          0x2b8e120  ccl::Device::gpu_queue_create()
    @          0x3390629  ccl::PathTraceWorkGPU::PathTraceWorkGPU()
    @          0x338ad04  ccl::PathTraceWork::create()
    @          0x33843e2  (unknown)
    @          0x33846c6  ccl::PathTrace::PathTrace()
    @          0x331b6e1  ccl::Session::Session()
    @          0x2b0cdd5  ccl::BlenderSession::create_session()
    @          0x2b0d990  ccl::BlenderSession::reset_session()
    @          0x2b0579d  (unknown)
    @          0x9eca874  (unknown)
    @          0x9e84cd8  _PyObject_MakeTpCall
    @          0x112b66f  _PyEval_EvalFrameDefault
    @          0x9f43364  (unknown)
    @          0x112b61a  _PyEval_EvalFrameDefault
    @          0x9f43364  (unknown)
    @          0x9e8495f  PyVectorcall_Call
    @          0x1a4d828  (unknown)
    @          0x19c0d66  (unknown)
    @          0x977aec9  (unknown)
    @          0x977bb04  RE_engine_render
    @          0x977f637  (unknown)
    @          0x97826a0  (unknown)
    @          0x978325c  RE_RenderAnim
    @          0x112e010  (unknown)
    @          0xb26e407  BLI_args_parse
    @          0x101c46b  main
    @     0x7f34eb952c87  __libc_start_main
    @          0x112d97c  (unknown)

**Comment by martenzander** [comment]
having the same issue...

**Comment by biliboomboom** [comment]
having the issue too!

**Comment by YuZhang-steven** [comment]
Also got this bug

**Comment by cperry-goog** [comment]
https://www.youtube.com/watch?v=hMCE6-ddTdY

**Comment by YuZhang-steven** [comment]
> https://www.youtube.com/watch?v=hMCE6-ddTdY appears to have some good suggestions

I tried it and changed the option to CUDA, but still doesn't work

**Comment by martenzander** [comment]
> https://www.youtube.com/watch?v=hMCE6-ddTdY appears to have some good suggestions

Seams to work. Can't use 'OPTIX' anymore but 'CUDA'. Important part is not to execute Blender using sudo

**Comment by YuZhang-steven** [comment]
> > https://www.youtube.com/watch?v=hMCE6-ddTdY appears to have some good suggestions
> 
> Seams to work. Can't use 'OPTIX' anymore but 'CUDA'. Important part is not to execute Blender using sudo

Thanks. yes it works without sudo and OPTIX can't work

**Comment by faruknane** [comment]
I'm having the same error! Also, I can no longer train deep learning models by running external python files. I think Google Colab prevents us from using external files. A code snippet works in a cell but the same code won't work by running a python file.

**Comment by shiftek-hosting** [comment]
Good morning ! I found a solution to reuse OptiX which remains a significant comfort. You just need to **update the Nvidia driver** released a few days ago.

To start, obviously **you can continue to use CUDA when launching Blender without "sudo"**
For people who want to update CUDA, just use the command:
`!sudo apt install cuda`

I think Google will apply the update but in the meantime, **update Nivida drivers with these commands** : 

`!sudo apt-get purge nvidia*
!sudo add-apt-repository ppa:graphics-drivers/ppa -y
!sudo apt-get update
!sudo apt install nvidia-driver-510 nvidia-dkms-510 -y
`

(It is possible that in the future the version will have changed. Check the version suitable for your graphics card. The 510 was obvious since the latest version is 510.73.08). 

Have fun with rendering ! o/

**Comment by faruknane** [comment]
@shiftek-hosting Thank you! Good morning to you too. I have also found a solution, wanted to share:

```
!sudo apt install libnvidia-gl-510 nvidia-dkms-510 nvidia-kernel-source-510 libnvidia-compute-510 libnvidia-extra-510 nvidia-compute-utils-510 libnvidia-decode-510 libnvidia-encode-510 nvidia-utils-510 xserver-xorg-video-nvidia-510 libnvidia-cfg1-510 libnvidia-fbc1-510

!sudo apt install nvidia-driver-510-server --yes
```
