### ISSUE TITLE
Spacy has stopped working

### ISSUE THREAD

**Issue by ale0xb** [googlecolab/colabtools#371]
Spacy has stopped working in Colab, I'm consistently getting the following error (seems to be related to CUDA, but I haven't enabled CUDA nor I'm using a GPU-accelerated environment:

`nlp = spacy.load('en')

doc = nlp(text) --> This fails` 

This seems to be related:
https://github.com/explosion/spaCy/issues/2778

> Exception ignored in: <bound method Stream.__del__ of <cupy.cuda.stream.Stream object at 0x7f6acc472e80>>
> Traceback (most recent call last):
>   File "cupy/cuda/stream.pyx", line 161, in cupy.cuda.stream.Stream.__del__
> AttributeError: 'Stream' object has no attribute 'ptr'
> ---------------------------------------------------------------------------
> CUDARuntimeError                          Traceback (most recent call last)
> <ipython-input-21-1b46715ea916> in <module>()
>      20   for keyword in row.author_keywords_list:
>      21 #     print('-' + keyword)
> ---> 22     keyword_nlp = nlp(keyword)
>      23 #     if len(keyword_nlp) > 1:
>      24 #       should_exit = True
> 
> /usr/local/lib/python3.6/dist-packages/spacy/language.py in __call__(self, text, disable)
>     344             if not hasattr(proc, '__call__'):
>     345                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
> --> 346             doc = proc(doc)
>     347             if doc is None:
>     348                 raise ValueError(Errors.E005.format(name=name))
> 
> nn_parser.pyx in spacy.syntax.nn_parser.Parser.__call__()
> 
> nn_parser.pyx in spacy.syntax.nn_parser.Parser.parse_batch()
> 
> /usr/local/lib/python3.6/dist-packages/spacy/util.py in get_cuda_stream(require)
>     236 
>     237 def get_cuda_stream(require=False):
> --> 238     return CudaStream() if CudaStream is not None else None
>     239 
>     240 
> 
> cupy/cuda/stream.pyx in cupy.cuda.stream.Stream.__init__()
> 
> cupy/cuda/runtime.pyx in cupy.cuda.runtime.streamCreate()
> 
> cupy/cuda/runtime.pyx in cupy.cuda.runtime.streamCreate()
> 
> cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()
> 
> CUDARuntimeError: cudaErrorUnknown: unknown error

**Comment by colaboratory-team** [comment]
Thanks for reporting. As a workaround until this is fixed you can request a GPU VM. FTR this worked for me just now:

```
!python -m spacy download en

# Workaround for https://github.com/explosion/spaCy/issues/2995
!pip install 'msgpack<0.6.0'

import spacy
nlp = spacy.load('en')
doc = nlp("A text-processing pipeline. Usually you'll load this once per process, and pass the instance around your application.") 
```

**Comment by colaboratory-team** [comment]
A simpler workaround: before importing anything (or right after executing "reset all runtimes"):
`!pip uninstall -qy cupy_cuda92`

This makes the above snippet work on non-GPU notebooks as well.

**Comment by colaboratory-team** [comment]
Now fixed, and this works without any uninstall of cupy_cuda92 or explicit pinning of msgpack:

```
!python -m spacy download en

import spacy
nlp = spacy.load('en')
doc = nlp("A text-processing pipeline. Usually you'll load this once per process, and pass the instance around your application.") 
```

Thanks for reporting!

**Comment by Ayush-agar** [comment]
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

I'm getting this error. Even though it says 
*Requirement already satisfied: en_core_web_lg==2.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.1.0/en_core_web_lg-2.1.0.tar.gz#egg=en_core_web_lg==2.1.0 in /usr/local/lib/python3.6/dist-packages (2.1.0)
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')*
When I downloaded en_core_web_lg in a cell just above that.

**Comment by jakevdp** [comment]
I was able to reproduce this error if I imported spacy *before* running ``!python -m spacy download en_core_web_lg``, but the package loaded successfully if I imported spacy *after* running the command. I suspect spacy does some import-time cataloging of available resources. I would suggest restarting your runtime (*Runtime→Restart Runtime*) then run the loading code again.
