### ISSUE TITLE
OutOfMemoryError: CUDA out of memory. Tried to allocate 968.00 MiB (GPU 0; 14.75 GiB total capacity; 12.50 GiB already allocated; 542.81 MiB free; 13.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by Med-Rokaimi** [googlecolab/colabtools#3814]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
I am not sure which GPU you selected, but if you used the lower end GPU, you can select premium GPUs with High-Ram at `Runtime` -> `Change runtime type`.

**Comment by Med-Rokaimi** [comment]
Thank you for your reply. I changed some parameter values in my code and it worked.
