### ISSUE TITLE
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above

### ISSUE THREAD

**Issue by reiinakano** [googlecolab/colabtools#384]
This error appeared with Python 2.7 using GPU. It's odd because the code was working, then when I did "Reset all runtimes", it got this error. I suspect I might've been assigned to a new machine with a broken cudnn configuration.
```
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv_vae_1/enc_conv1/Conv2D (defined at <ipython-input-6-ef2449ecdccc>:101)  = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ones, conv_vae/enc_conv1/kernel/read)]]
```

Related unanswered SO question: https://stackoverflow.com/questions/53414185/google-colab-error-failed-to-get-convolution-algorithm-this-is-probably-becaus

**Comment by NitzanBusany** [comment]
Same Error.
It is happening only on GPU mode.

**Comment by colaboratory-team** [comment]
Sorry for the trouble. Can you share an example notebook that reproduces the problem?

**Comment by MilanCugur** [comment]
Hi everyone, tonight I received the same error too.

An error occurs on all of my notebooks (which use GPU, Puthon3) - That notebooks I successfully run last night.

I got: 
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv2d_1/convolution_grad/Conv2DBackpropFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
	 [[{{node loss/mul/_283}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2036_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Any idea? Maybe some Colab update in last couple of hours?

Thanks in advance,
Milan

**Comment by reddragon** [comment]
Happening for me too.

**Comment by colaboratory-team** [comment]
Thanks for the repro. We're looking into this now.

**Comment by mfox94** [comment]
Happening the same of me. I hope it is a temporary error..

**Comment by frk19** [comment]
I am facing the same problem.

**Comment by colaboratory-team** [comment]
We've reverted a recent service change that caused this issue. (The notebook [upthread](https://github.com/googlecolab/colabtools/issues/384#issuecomment-450975709) is again working.)

If you have an existing backend, you'll need to request a new one in order to pick up the fix. To reset your backend, use the 'Reset all runtimes' item in the runtime menu.

![reset_runtimes](https://user-images.githubusercontent.com/38081706/50615269-9c344580-0e98-11e9-943c-d38ff8f76a7f.png)

**Comment by MilanCugur** [comment]
Thank you guys, now its working.
Great job!

**Comment by NitzanBusany** [comment]
Fixed! Thank you.

**Comment by Ajcaico** [comment]
This same issue seemed to reappear for me. I've been using a CNN model just fine and then started receiving the same error mentioned above a few days ago. 
Is it possible another service change has caused this?

**Comment by iuliakhomenko** [comment]
Same issue here

**Comment by colaboratory-team** [comment]
@Ajcaico / @iuliakhomenko : can either of you share a minimal notebook reproducing the issue (ideally without using private data)?

**Comment by colaboratory-team** [comment]
@Ajcaico thanks but that notebook: relies on files in your Drive, does a ton of unrelated things, and doesn't show the error message in question. Are you able to isolate a minimal subset of it that triggers the error without using your private data (which is not readable to others)?

**Comment by colaboratory-team** [comment]
It'd still be great to get a minimal, self-contained (no drive data) reproduction notebook, but also:
The cited cudnn error can _also_ be raised if cudnn is the first thing to be tried after any other lib/op runs the GPU out of RAM. If reducing batch/step/data size makes the cudnn error go away that's a good indication that that's what's going wrong.

**Comment by Ajcaico** [comment]
I created a separate colab notebook with the same model and a subset of data. The cuDNN errors does not occur there. When I try the same subset of data in the original notebook, I get the cuDNN error even after retarting the runtime. I have ran the GPU out of RAM in the original notebook before, but have restarted runtime. Could it be that notebook is corrupted somehow? I will try to copy all the cells of that notebook into a new one.

**Comment by colaboratory-team** [comment]
It would be very surprising for a notebook to be "corrupt" in a way that held on to GPU RAM.
You refer to "restarting" runtimes - to be sure you should use "Reset all runtimes" to get a freshly-minted VM (as opposed to "Restart runtime", which just restarts the python process your notebook is using so e.g. GPU RAM may still be held by processes other than your runtime).

**Comment by TOSUKUi** [comment]
I just got same error, and is still not fixed by “reset all runtimes” .
I am using tensorflow.keras and tensorflow version is 2.0.0a.
My colaboratory is using cudnn7.5 and cuda10.0 confirmed by usr/include/cudnn.h and nvcc -V.

**Comment by TOSUKUi** [comment]
I resolve above issue by sort tensorflow and tensorflow-gpu version to 1.13.1

**Comment by trancenoid** [comment]
Any updates on this issue ? I am having the same problem, the same notebook was working fine 10 day ago, please help. I have tried resetting the runtime multiple times

**Comment by Ajcaico** [comment]
Even after resetting the runtime in the collab notebook I was still getting the same error. I had to copy the code into a fresh new collab notebook and then it worked.

**Comment by AnimeshSahoo** [comment]
Please google collab team help me out from this problem, yesterday my model was running fine but now it's showing the same  error!! even after resetting the runtime.

**Comment by metriczulu** [comment]
I'm also having the exact same issue.  Even Colab notebooks that worked previously are no longer working.  Tried reverting to older version of TF and it is still not working.  Pretty ironic that Francois Chollet was on Twitter talking trash about PyTorch yesterday and saying no one will remember it in 5 years and Google can't even keep their deep learning library working on their own VM instances.

**Comment by colaboratory-team** [comment]
If this issue is recurring, it's likely to be a distinct cause. Please open a distinct issue with a self-contained notebook that reproduces the problem and we'll take a closer look.
