### ISSUE TITLE
No setup.py/pyproject.toml used, copying full private data into .apk.

### ISSUE THREAD

**Issue by dariobio** [googlecolab/colabtools#4330]
**Describe the current behavior**
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
[DEBUG]:   	<-------------> 0% WAITING> IDLE> IDLE
[INFO]:    STDOUT (last 20 lines of 52):
	       - changing `org.gradle.java.home` in `gradle.properties`.	

**Describe the expected behavior**
should be able to have the new version

<-------------> 0% WAITING> IDLE> IDLE
[INFO]:    STDERR:
	
[INFO]:    ENV:
export SHELL='/bin/bash'
export NV_LIBCUBLAS_VERSION='12.2.5.6-1'
export NVIDIA_VISIBLE_DEVICES='all'
export COLAB_JUPYTER_TRANSPORT='ipc'
export NV_NVML_DEV_VERSION='12.2.140-1'
export NV_CUDNN_PACKAGE_NAME='libcudnn8'
export CGROUP_MEMORY_EVENTS='/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events'
export NV_LIBNCCL_DEV_PACKAGE='libnccl-dev=2.19.3-1+cuda12.2'
export NV_LIBNCCL_DEV_PACKAGE_VERSION='2.19.3-1'
export VM_GCE_METADATA_HOST='169.254.169.253'
export HOSTNAME='7cd37d2ca821'
export LANGUAGE='en_US'
export TBE_RUNTIME_ADDR='172.28.0.1:8011'
export GCE_METADATA_TIMEOUT='3'
export NVIDIA_REQUIRE_CUDA='cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526'
export NV_LIBCUBLAS_DEV_PACKAGE='libcublas-dev-12-2=12.2.5.6-1'
export NV_NVTX_VERSION='12.2.140-1'
export COLAB_JUPYTER_IP='172.28.0.12'
export NV_CUDA_CUDART_DEV_VERSION='12.2.140-1'
export NV_LIBCUSPARSE_VERSION='12.1.2.141-1'
export COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL='http://172.28.0.1:8013/'
export NV_LIBNPP_VERSION='12.2.1.4-1'
export NCCL_VERSION='2.19.3-1'
export KMP_LISTEN_PORT='6000'
export TF_FORCE_GPU_ALLOW_GROWTH='true'
export ENV='/root/.bashrc'
export PWD='/content'
export COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT='30s'
export TBE_EPHEM_CREDS_ADDR='172.28.0.1:8009'
export TBE_CREDS_ADDR='172.28.0.1:8008'
export NV_CUDNN_PACKAGE='libcudnn8=8.9.6.50-1+cuda12.2'
export NVIDIA_DRIVER_CAPABILITIES='compute,utility'
export COLAB_JUPYTER_TOKEN=''
export LAST_FORCED_REBUILD='20240122'
export NV_NVPROF_DEV_PACKAGE='cuda-nvprof-12-2=12.2.142-1'
export NV_LIBNPP_PACKAGE='libnpp-12-2=12.2.1.4-1'
export NV_LIBNCCL_DEV_PACKAGE_NAME='libnccl-dev'
export TCLLIBPATH='/usr/share/tcltk/tcllib1.20'
export NV_LIBCUBLAS_DEV_VERSION='12.2.5.6-1'
export COLAB_KERNEL_MANAGER_PROXY_HOST='172.28.0.12'
export NVIDIA_PRODUCT_NAME='CUDA'
export NV_LIBCUBLAS_DEV_PACKAGE_NAME='libcublas-dev-12-2'
export USE_AUTH_EPHEM='1'
export NV_CUDA_CUDART_VERSION='12.2.140-1'
export COLAB_WARMUP_DEFAULTS='1'
export HOME='/root'
export LANG='en_US.UTF-8'
export COLUMNS='100'
export CUDA_VERSION='12.2.2'
export CLOUDSDK_CONFIG='/content/.config'
export NV_LIBCUBLAS_PACKAGE='libcublas-12-2=12.2.5.6-1'
export NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE='cuda-nsight-compute-12-2=12.2.2-1'
export COLAB_RELEASE_TAG='release-colab_20240123-060155_RC00'
export PYDEVD_USE_FRAME_EVAL='NO'
export KMP_TARGET_PORT='9000'
export CLICOLOR='1'
export KMP_EXTRA_ARGS='--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/m-s-2465dwuy120ak --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true'
export NV_LIBNPP_DEV_PACKAGE='libnpp-dev-12-2=12.2.1.4-1'
export COLAB_LANGUAGE_SERVER_PROXY_LSP_DIRS='/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages'
export NV_LIBCUBLAS_PACKAGE_NAME='libcublas-12-2'
export COLAB_KERNEL_MANAGER_PROXY_PORT='6000'
export CLOUDSDK_PYTHON='python3'
export NV_LIBNPP_DEV_VERSION='12.2.1.4-1'
export ENABLE_DIRECTORYPREFETCHER='1'
export NO_GCE_CHECK='False'
export JPY_PARENT_PID='77'
export PYTHONPATH='/env/python'
export TERM='xterm-color'
export NV_LIBCUSPARSE_DEV_VERSION='12.1.2.141-1'
export GIT_PAGER='cat'
export LIBRARY_PATH='/usr/local/cuda/lib64/stubs'
export NV_CUDNN_VERSION='8.9.6.50'
export SHLVL='0'
export PAGER='cat'
export COLAB_LANGUAGE_SERVER_PROXY='/usr/colab/bin/language_service'
export NV_CUDA_LIB_VERSION='12.2.2-1'
export NVARCH='x86_64'
export NV_CUDNN_PACKAGE_DEV='libcudnn8-dev=8.9.6.50-1+cuda12.2'
export NV_CUDA_COMPAT_PACKAGE='cuda-compat-12-2'
export MPLBACKEND='module://ipykernel.pylab.backend_inline'
export NV_LIBNCCL_PACKAGE='libnccl2=2.19.3-1+cuda12.2'
export LD_LIBRARY_PATH='/usr/local/nvidia/lib:/usr/local/nvidia/lib64'
export COLAB_GPU=''
export GCS_READ_CACHE_BLOCK_SIZE_MB='16'
export NV_CUDA_NSIGHT_COMPUTE_VERSION='12.2.2-1'
export NV_NVPROF_VERSION='12.2.142-1'
export LC_ALL='en_US.UTF-8'
export COLAB_FILE_HANDLER_ADDR='localhost:3453'
export PATH='/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin'
export NV_LIBNCCL_PACKAGE_NAME='libnccl2'
export COLAB_DEBUG_ADAPTER_MUX_PATH='/usr/local/bin/dap_multiplexer'
export NV_LIBNCCL_PACKAGE_VERSION='2.19.3-1'
export PYTHONWARNINGS='ignore:::pip._internal.cli.base_command'
export DEBIAN_FRONTEND='noninteractive'
export COLAB_BACKEND_VERSION='next'
export OLDPWD='/'
export _='/usr/local/bin/buildozer'
export PACKAGES_PATH='/root/.buildozer/android/packages'
export ANDROIDSDK='/root/.buildozer/android/platform/android-sdk'
export ANDROIDNDK='/root/.buildozer/android/platform/android-ndk-r25b'
export ANDROIDAPI='31'
export ANDROIDMINAPI='21'
export ANDROID_NDK_HOME='/root/.buildozer/android/platform/android-ndk-r25b'
export ANDROID_HOME='/root/.buildozer/android/platform/android-sdk'

[INFO]:    COMMAND:
cd /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/MYApp&& /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/MYAPP/gradlew clean assembleDebug

**Comment by EvanWiederspan** [comment]
This doesn't seem like a Colab issue, I would ask on Stack Overflow or a similar forum

**Comment by dariobio** [comment]
I solved it with this command and it worked
!sudo apt-get update
!sudo apt-get upgrade
