### ISSUE TITLE
Recent updates causing cuda issues

### ISSUE THREAD

**Issue by feigur** [googlecolab/colabtools#5079]
I am using Mamba2_ssm with some torch on a A100 instance, has been working great, until today, even after recompiling the Mamba2 package, which was a fix I had been using until it stopped working a few days ago, but just as that happened, then !pip install mamba2_ssm started working again, just for everything to break, with this cuda error

I am months into this project and this tends to happen from time to time, 2nd or 3rd time in half a year that the cuda versions break (for me at least) with just mamba2 and casual_conv1d pips, with trition working in their backend, some times it does not matter if I pre-compile or pip the packages, for it to just fix it self eventually

Timestamp,Level,Message
"Jan 30, 2025, 7:46:25 PM",WARNING,WARNING:root:kernel b1fcd665-86b4-4af4-9061-b3a5db62c3b9 restarted
"Jan 30, 2025, 7:46:25 PM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"Jan 30, 2025, 7:46:23 PM",WARNING,Could not load symbol cudnnGetLibConfig. Error: /usr/local/lib/python3.11/dist-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_graph.so.9: undefined symbol: cudnnGetLibConfig
"Jan 30, 2025, 7:41:43 PM",INFO,"Kernel started: b1fcd665-86b4-4af4-9061-b3a5db62c3b9, name: python3"

https://github.com/state-spaces/mamba

**Comment by feigur** [comment]
Looked better into it, as it stopped instantly restarting the session, and this just seems like a generic torch error, likely due to some updates as it worked fine a day or 2 ago.... also had issues with torchaudio

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-42-79f09fa5679a>](https://localhost:8080/#) in <cell line: 0>()
     81       diffusion_model.train()
     82       print('12')
---> 83       loss = diffusion_model.train_step(
     84           input_data=input_audio,
     85           tag=input_tags,

7 frames
[<ipython-input-38-83224efc8942>](https://localhost:8080/#) in train_step(self, input_data, tag, adsr, octive, note, target, optimizer, criterion, mask, N, debug)
    808 
    809             print('12345')
--> 810             denoised_output = self.driver(noisy_input, t_steps, tag, adsr, octive, note, debug=debug)
    811 
    812             if debug:

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1734             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735         else:
-> 1736             return self._call_impl(*args, **kwargs)
   1737 
   1738     # torchrec tests the code consistency with the following code

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1745                 or _global_backward_pre_hooks or _global_backward_hooks
   1746                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747             return forward_call(*args, **kwargs)
   1748 
   1749         result = None

[<ipython-input-38-83224efc8942>](https://localhost:8080/#) in forward(self, audio_input, timestep, tag, adsr, octive, note, debug)
    334           self.debug_size(audio_input, "audio_input")
    335           self.debug_size(adsr, "adsr")
--> 336         audio_output = self.conv_audio_layer(audio_input)
    337         #audio_output = self.audio_cnn_layer_norm(audio_output.permute(0, 2, 1)).permute(0, 2, 1)
    338         #audio_output = F.silu(audio_output)  # Or F.silu for Swish

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1734             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735         else:
-> 1736             return self._call_impl(*args, **kwargs)
   1737 
   1738     # torchrec tests the code consistency with the following code

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1745                 or _global_backward_pre_hooks or _global_backward_hooks
   1746                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747             return forward_call(*args, **kwargs)
   1748 
   1749         result = None

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in forward(self, input)
    373 
    374     def forward(self, input: Tensor) -> Tensor:
--> 375         return self._conv_forward(input, self.weight, self.bias)
    376 
    377 

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    368                 self.groups,
    369             )
--> 370         return F.conv1d(
    371             input, weight, bias, self.stride, self.padding, self.dilation, self.groups
    372         )

RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_SUBLIBRARY_LOADING_FAILED

**Comment by metrizable** [comment]
@feigur Thanks for filing the issue and thanks for using Colab.

Are you able to provide a minimal reproducible example so that we can help troubleshoot and debug?

**Comment by sensei12** [comment]
Hello,

Just plain CUDA C programming is working well last Monday (Jan 27), but when I went back to using it, all my CUDA-based program says no GPU kernel to profile.

Whenever the foobar<<<x,y>>> () is called, the GPU kernel is not executing.

Sample.. simple program not working

```
#include <stdio.h>

__global__
void hello()
{
    printf("Hello World, I am thread %d from block %d, blockDim.x = %d, gridDim.x = %d \n",threadIdx.x, blockIdx.x, blockDim.x, gridDim.x);
}

int main() {
    int numBlocks = 2;
    int numThreads = 16;
    hello<<<numBlocks,numThreads>>>();
    cudaDeviceSynchronize();
    return 0; 
```
Compilation:
```
%%shell
nvcc hello.cu -o hello
```

**Comment by feigur** [comment]
@metrizable not really, I am not able to recreate the error outside my extensive code-base, which I have not changed since it last worked, I will admit that this may be my own fault, but I highly doubt it, as I have not been making changes and just been training. As I mentioned earlier this is also not the first time I get random cuda errors on colab

**Comment by feigur** [comment]
After updating triton, along with things, the code start behaving correctly, I wish I could give you a more concrete answer, but this project has far surpassed my ability to fully decode the complexities that may cause these issues, but I continue asserting that this is a versioning issue on colab, as it keeps happening when colab is updated, although it may not effect "normal use"

**Comment by metrizable** [comment]
@feigur Glad to hear that you were able to resolve the issue by updating `triton` and other things. Given that the Colab runtimes updated CUDA version in #5061 , it's likely that your code base was using an older, incompatible `triton` and other.
