### ISSUE TITLE
cupy not working

### ISSUE THREAD

**Issue by duboism** [googlecolab/colabtools#5166]
**Describe the current behavior**
`cupy` (from standard runtime) doesn't work. For instance `cp.cuda.is_available()` raises `cudaErrorInsufficientDriver`. It seems a backend issue.

**Describe the expected behavior**
I expect `cupy` to work or instruction on how to make it work.

**What web browser you are using**
Firefox.

**Additional context**
See Gist at: https://colab.research.google.com/gist/duboism/9d9ddf0efb9f5127f166ef54a3a4ca41/issue-5166.ipynb

**Comment by duboism** [comment]
This is my first issue here so if you need more information, don't hesitate.

**Comment by metrizable** [comment]
@duboism Thanks for filing the issue and thanks for using Colab.

I used your Gist and could not replicate your issue:

![Image](https://github.com/user-attachments/assets/38178f7b-f8a2-488a-8be3-622bc348a268)

However, I was able replicate it if I had selected CPU runtime:

![Image](https://github.com/user-attachments/assets/ba933338-838a-46c2-9e42-fde8273ffc21)

Can you confirm you are connected to a GPU runtime by opening the Runtime > Change runtime type menu item and selecting a GPU accelerator?

**Comment by duboism** [comment]
Thanks for you response. I confirm that it works if I select a GPU runtime (I was not aware of this option).

Maybe it's more a question for `cupy` dev but shouldn't `cupy` be able to detect that there is no GPU without failing?

**Comment by metrizable** [comment]
Yes, reasonable. Here's something I just noticed, and is a bit strange. If I execute `cp.cuda.is_available()` a second time, it properly provides `False` on CPU runtimes:

![Image](https://github.com/user-attachments/assets/494e54c6-6835-4b69-812a-08a0ddd89ace)

Clicking into the `is_available()` method link from the stack in Colab, I see the method is testing one string, but not matching the exception's message in this case. And I see the method is also setting the global `_available` to `False` on first pass, which would explain the behavior above.

![Image](https://github.com/user-attachments/assets/689e6e81-27aa-4335-b1d4-9a82f9521af4)

I believe this might be a cool PR upstream someone could author with cupy, or at the very least, file a bug.

**Comment by duboism** [comment]
Yes, I noticed that too but it was so surprising that I thought it came from Colab (therefore I didn't talk about it to not clutter the issue). Thanks for you help, I will open an issue on `cupy`.

**Comment by duboism** [comment]
I think that cupy/cupy#6702 already covered this so I added comment there. I may take time to address this.

**Comment by duboism** [comment]
> I think that [cupy/cupy#6702](https://github.com/cupy/cupy/issues/6702) already covered this so I added comment there. I may take time to address this.

This issue is closed and should be released with cupy 14.0.0.
