### ISSUE TITLE
estimator.train hangs indefinitely on TPU

### ISSUE THREAD

**Issue by gaphex** [googlecolab/colabtools#539]
- Describe the current behavior:
Calling estimator.train on a TPU Colab instance hangs without any error or warning messages.
Previously, I was able to execute the exact same code with no issue.

- Describe the expected behavior:
The estimator model proceeds with training as usual, printing logging messages along the way.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

- Link to self-contained notebook that reproduces this issue
https://colab.research.google.com/drive/18GgLUb1qwJDC6K1UUt7grLby5N0lVwy_

**Comment by gaphex** [comment]
I am getting the same behaviour when using a GPU accelerator as well.

**Comment by gaphex** [comment]
The problem was resolved by creating a new model, then copying over the 'data' and 'index' files from the old run. After that the training proceeded as usual.
My best guess: there was a data corruption issue with either 'meta' or 'graph.pbtxt' file.
This is likely an problem with tensorflow, not Colab, so I am closing this issue.
